#!/usr/bin/env python

import subprocess
import sys
from pullme import (
    load_settings,
    check_outstanding_changes,
    determine_head_branch,
    push_to_personal,
    determine_base_branch,
    github_path_from_remote_name,
    make_pull_request,
)

def main():
    settings = load_settings()
    check_outstanding_changes(settings)
    head_branch = determine_head_branch()
    push_to_personal(settings, head_branch)
    base_branch = determine_base_branch(settings)
    upstream_github_path = github_path_from_remote_name(settings['upstream'])
    personal_github_path = github_path_from_remote_name(settings['personal'])
    make_pull_request(settings, upstream_github_path, personal_github_path, base_branch, head_branch)

try:
    main()
except subprocess.CalledProcessError, e:
    sys.exit(e.returncode)

